import type { Metadata } from 'next';
import { DM_Sans } from 'next/font/google';
import './globals.css'; // Import global styles

const dmSans = DM_Sans({
  subsets: ['latin'],
});

export const metadata: Metadata = {
  title: 'My App', // Replace with your app's title
  description: 'Generated by create next app', // Replace with your app's description
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`${dmSans.className} antialiased`}>{children}</body>
    </html>
  );
}
